name: Binder
on: [push]

jobs:
  Create-MyBinderOrg-Cache:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger MyBinder Build
      run: |
        curl -L "https://mybinder.org/build/gh/${{ github.repository }}/${{ github.ref_name }}"
